system:
  dataset_type: WFN  # WFN / GW / BSE
  flows_dir: "Deep-GWBSE/examples/flows"  # directory to all materials
  dataset_dir: "Deep-GWBSE/src/from_model/dataset"  # directory to save dataset
  dataset_fname: "dataset_WFN_cplx_test.h5"
  multiprocessing: True

WFN:  # wfn shape (nk, nb, H, W, [2]): H - height, W - width, last 2: re/im for complex wfn
  cell_slab_truncation: 60  # number of pixels to remain along z direction
  useWignerXY: True  # if True, transform to Wigner cell along x&y. 3D: useWignerXYZ
  AngstromPerPixel: 0.1  # Angstrom / Pixel along xy
  AngstromPerPixel_z: 0.1  # Angstrom / Pixel along z
  upsampling_factor: 3  # upsampling along xy for interpolation in wigner cell
  nv_wfn: 2  # number of valence bands in wfn
  nc_wfn: 6  # number of conduction badns in wfn

GW:  # WFN params are inherited from WFN section (ignoring nc/nv_wfn)
  nv_sigma: 1  # number of valence badns in GW
  nc_sigma: 1  # number of conduction bands in GW
  prediction_only: False

BSE:
  prediction_only: False

